language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
  - echo "deb http://dl.bintray.com/siegfried/debian wheezy main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update && sudo apt-get install siegfried
install:
  - pip install inquirer
  - pip install codecov
script:
  - python test.py
after_success:
  - codecov
